name: mpmpytorch_deform
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas
  - tqdm
  - scikit-image
  - scikit-learn
  - trimesh
  - meshplot
  - pip
  - ipykernel
  - jupyterlab 
  - pythreejs
  - pip:
      - embreex
      - pyembree
      - mpm-pytorch
      - open3d

